### ISSUE TITLE
Disable Hystrix not work

### ISSUE THREAD

**Issue by ighilr** [kptfh/feign-reactive#10]
Hello, I am currently using your repo but unfortunately I can not disable Hystrix with the configuration: feign.hystrix.enabled = false.
there is always the circuit breaker that is active with the fallback. 
I also can not disable the timeout.
could you help me please ?

Thanks

**Comment by kptfh** [comment]
Hi @ighilr. Have a look at this [documentation ](https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration)
`set reactive.feign.hystrix.enabled to false to disable hystrix configuration for all clients`

**Comment by ighilr** [comment]
Thank you. it works. On the other hand there is always the timeout which does not want to be deactivated because there is always a latency time during the first request GET for example. Do you know why ?

**Comment by kptfh** [comment]
Your last comment is not clear to me. Do you mean that now you have timeout exception while running first request?

**Comment by ighilr** [comment]
When I launch my application and I launch a first GET or POST requeste there is a latency before having an answer. There is a timeout, whether for a status 200, 201, 400, 404 or 500.
Thanks

**Comment by kptfh** [comment]
can you put stacktrace with timeout exception here?

**Comment by ighilr** [comment]
nothing in the log

**Comment by ighilr** [comment]
I restarted all my services. There is no more timeout. Thank you
