### ISSUE TITLE
@RequestLine("GET /icecream/flavors")

### ISSUE THREAD

**Issue by kamilgregorczyk** [kptfh/feign-reactive#2]
Hi, in the readme file you are using unknown annotations (at least, to me) like `@RequestLine("GET /icecream/flavors")` which dependency contains them?

**Comment by kptfh** [comment]
<dependency>
        <groupId>io.github.openfeign</groupId
        <artifactId>feign-core</artifactId>
        <version>9.5.1</version>
 </dependency>

**Comment by kamilgregorczyk** [comment]
Hi, thanks, please consider adding it to the manual.
