### ISSUE TITLE
feign-reactive-core not found in custom repo

### ISSUE THREAD

**Issue by kamilgregorczyk** [kptfh/feign-reactive#3]
Hi, for some reason maven cannot download/find this repo, I added 

```
<repositories>
    <repository>
      <id>bintray-kptfh-feign-reactive</id>
      <name>bintray</name>
      <url>https://dl.bintray.com/kptfh/feign-reactive</url>
    </repository>
  </repositories>
``` 
in the project level and 

```
<dependency>
      <groupId>io.github.reactivefeign</groupId>
      <artifactId>feign-reactive-core</artifactId>
      <version>0.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.github.reactivefeign</groupId>
      <artifactId>feign-reactive-cloud</artifactId>
      <version>0.6.0</version>
    </dependency>
``` 
in the dependencies section but for some reason I'm getting:
```Could not resolve dependencies for project com.kgregorczyk.store_example:product:jar:0.0.2: Could not find artifact io.github.reactivefeign:feign-reactive:jar:0.6.0 in bintray-kptfh-feign-reactive ```

Here's my full pom file https://pastebin.com/pMHibgkw

**Comment by kptfh** [comment]
Hi! You can check artifacts here [https://bintray.com/kptfh/feign-reactive/client/0.6.0#files](https://bintray.com/kptfh/feign-reactive/client/0.6.0#files)

**Comment by kamilgregorczyk** [comment]
Hi, I'm getting 404 with your link

**Comment by kptfh** [comment]
Sorry. Try this one [https://bintray.com/kptfh/feign-reactive/client/0.6.1#files](https://bintray.com/kptfh/feign-reactive/client/0.6.1#files)

**Comment by kamilgregorczyk** [comment]
Thanks!
